### ISSUE TITLE
stylegan/stylegan-xl-utils/feature_networks/clip/bpe_simple_vocab_16e6.txt.gz'

### ISSUE THREAD

**Issue by daxu0111** [TsingZ0/FedKTL#1]
When running the project, an error is reported saying that this file does not exist. Where can I download this file?

**Comment by TsingZ0** [comment]
Please download the latest version of the code :-), where `stylegan-xl-utils` has been renamed to `stylegan-utils`.

**Comment by XXiaoY** [comment]
> When running the project, an error is reported saying that this file does not exist. Where can I download this file?


Have you successfully reproduced it??

**Comment by tuichong** [comment]
> > When running the project, an error is reported saying that this file does not exist. Where can I download this file?
> 
> Have you successfully reproduced it??

Do you have a try?
