### ISSUE TITLE
where is stable-diffusion/pipelines

### ISSUE THREAD

**Issue by chenrxi** [TsingZ0/FedKTL#2]
hi, where is stable-diffusion/pipelines? 
Besides, what's the usage of prompt_embeds and negative_prompt_embeds in the images generation?
![image](https://github.com/user-attachments/assets/4be763ca-9d8a-4e6a-b23d-4e52a8922abb)

**Comment by TsingZ0** [comment]
Apologies for the earlier mistaken update. The subsequent updates have removed the original file. You can find it in the earlier versions or the most recent version.

**Comment by chenrxi** [comment]
Thank your quick reply. Here are some points I am still confused about:
(1) FedKTL is agnostic to the semantics of the images produced by the generator, which means the generated images make no sense to humans.

**Comment by TsingZ0** [comment]
Yes, the generated clear images are only used to improve the extraction ability of clients' feature extractors.

**Comment by chenrxi** [comment]
Hi, I ask a question: Can it be applied into CLIP Finetuning? @TsingZ0
