### ISSUE TITLE
链接更新

### ISSUE THREAD

**Issue by YaxinCountry** [TsingZ0/FedKTL#3]
![image](https://github.com/user-attachments/assets/5274d0a1-db26-442a-a23c-d8f9f3f78894)
nin
您好，这些提供的链接大多无法使用，可以更新一下链接吗，非常感谢

**Comment by TsingZ0** [comment]
由于这些模型都较大，无法上传至GitHub。这些都是官方链接，如果失效那就没办法了。或许你可以自行搜索第三方链接。据我所知，Stable Diffusion被官方删库了，但这也是没办法的事情。
