### ISSUE TITLE
Environment Setup Issues: Missing `requirements.txt` and `torch_utils` Dependency

### ISSUE THREAD

**Issue by mesabo** [TsingZ0/FedKTL#4]
**Issue:**

I encountered several issues while trying to set up and run the project. The environment setup process seems incomplete or missing, making it difficult (or possibly impossible) to run the code as intended. Here are the specific problems I faced:

1. **Missing `requirements.txt` File**: There is no `requirements.txt` file or detailed setup instructions, which makes it challenging to install the correct versions of dependencies. Adding this file would significantly improve reproducibility and usability for other developers.

2. **Undocumented Usage of `torch_utils`**: The project appears to use `torch_utils` to import `gen_utils`, which cannot be installed directly via `pip` or Conda. This dependency lacks documentation or explanation on how to acquire or implement it, blocking the ability to execute the code successfully. Without further guidance, it’s unclear if this is an external library or if additional setup steps are required.

3. **Lack of Run Instructions**: There are no clear instructions on how to run the project after setup. Providing a basic guide, including examples or explanations of expected inputs and outputs, would be very helpful.

Given these issues, it’s difficult to verify or test the code effectively. Could you please:

- Add a `requirements.txt` file with all necessary dependencies and versions?
- Clarify the usage of `torch_utils` and include instructions to obtain or install it.
- Provide a brief guide on how to run the project, with sample commands or usage details.

These changes would greatly improve accessibility and allow others to explore and contribute to the project. Thank you!

**Comment by TsingZ0** [comment]
Hello, please refer to our other project for the environment setting, as mentioned in the [README](https://github.com/TsingZ0/FedKTL?tab=readme-ov-file#dataset--environments).

We have include all the necessary code for `torch_utils` in this project, see [here](https://github.com/TsingZ0/FedKTL/tree/main/system/stylegan/stylegan-utils/torch_utils). There is no Python package named `torch_utils` actually. If you cannot use `torch_utils` directly, you may need to explicitly set the path or your root folder. 

Please refer to [README](https://github.com/TsingZ0/FedKTL/tree/main?tab=readme-ov-file#training-and-evaluation) for run instructions.

Thanks for providing these valuable suggestions.

**Comment by mesabo** [comment]
Thank you.
That solved my problem!
